---
vagrantfile-local:
    vm:
        box: hashicorp/precise64
        hostname: null
        network:
            public_network: true
            forwarded_port:
                web:
                    host: '8080'
                    guest: '80'
        provider:
            virtualbox:
                modifyvm:
                    natdnshostresolver1: on
                    memory: '512'
                setextradata:
                    VBoxInternal2/SharedFoldersEnableSymlinksCreate/v-root: 1
        provision:
            puppet:
                manifests_path: .puppet/puppet
                manifest_file: manifest.pp
                options:
                    - '--verbose'
                    - '--hiera_config /vagrant/.puppet/puppet/hiera.yaml'
                    - '--parser future'
        synced_folder:
            vagrant:
                id: vagrant-root
                source: ./
                target: /var/www/vagrant
                type: 'smb'
    ssh:
        host: null
        port: null
        private_key_path: null
        username: vagrant
        guest_port: null
        keep_alive: true
        forward_agent: false
        forward_x11: false
        shell: 'bash -l'
    vagrant:
        host: detect
server:
    packages:
        - vim
    dot_files:
        -
            bash_aliases: null
    _prevent_empty: ''
mailcatcher:
    install: 0
    settings:
        smtp_ip: 0.0.0.0
        smtp_port: 1025
        http_ip: 0.0.0.0
        http_port: '1080'
        mailcatcher_path: /usr/local/bin
        log_path: /var/log/mailcatcher/mailcatcher.log
apache:
    install: '1'
    settings:
        user: www-data
        group: www-data
        default_vhost: true
        manage_user: false
        manage_group: false
        sendfile: 0
    modules:
        - php
        - rewrite
    vhosts:
        localhost:
            servername: localhost
            serveraliases:
                - '*'
            docroot: /var/wwwvagrant/public
            port: '80'
            override:
                - All
    mod_pagespeed: 0
    mod_spdy: 0
nginx:
    install: '0'
    vhosts:
        localhost:
            server_name: localhost
            www_root: /var/www/vagrant/public
            listen_port: '80'
            index_files:
                - index.php
hhvm:
    install: '0'
    nightly: '1'
    settings:
        host: 127.0.0.1
        port: '9000'
mysql:
    install: '1'
    root_password: vagrant
    phpmyadmin: 0
    adminer: 0
    databases:
        1gCDRTA6OojF:
            grant:
                - ALL
            name: vagrant
            host: localhost
            user: vagrant
            password: vagrant
            sql_file: ''
postgresql:
    install: 0
    settings:
        root_password: '123'
        user_group: postgres
        encoding: UTF8
        version: '9.3'
    databases: {  }
    adminer: 0
mariadb:
    install: 0
    root_password: '123'
    phpmyadmin: 0
    adminer: 0
    databases: {  }
    version: '10.0'
mongodb:
    install: 0
    settings:
        auth: 1
        port: '27017'
    databases: {  }
redis:
    install: 0
    settings:
        conf_port: '6379'
beanstalkd:
    install: 0
    settings:
        listenaddress: 0.0.0.0
        listenport: '13000'
        maxjobsize: '65535'
        maxconnections: '1024'
        binlogdir: /var/lib/beanstalkd/binlog
        binlogfsync: null
        binlogsize: '10485760'
    beanstalk_console: 0
    binlogdir: /var/lib/beanstalkd/binlog
rabbitmq:
    install: 0
    settings:
        port: '5672'
nodejs:
    install: '1'
    manage_repo: false
    version: 'latest'
    packages:
        - bower
        - less
